# Generated by Django 5.1.7 on 2025-03-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='This course has no description'),
        ),
        migrations.AddField(
            model_name='course',
            name='num_hours',
            field=models.IntegerField(default='This course has no description'),
            preserve_default=False,
        ),
    ]
