# Generated by Django 5.1.7 on 2025-03-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_description_course_num_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num_hours',
            field=models.IntegerField(default=0),
        ),
    ]
